name : Deploy
on:
  push:
    branches:
      - main
     
env:
  DOCKER_IMAGE: ghcr.io/${{ github.actor }}/kdt1-study-3-team4-back
  VERSION: ${{ github.sha }}
  NAME: kdt1-study-3-team4-back
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      ##jdk setting
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu' # https://github.com/actions/setup-java
         
      ## gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.propertise') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
     
      ## gradle build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build -x test
        
      ## docker build & push to production
      - name: Docker build & push to prod
        run: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{secrets.GHCR_TOKEN }}
            docker buildx create --name arm64builder --use
            docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t ghcr.io/reberel/kdt1-study-3-team4-back:latest --push .
            docker logout
     
  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, deploy-backend ]
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
       
      - name: Deploy to prod
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_PROD }}
          username: ec2-user
          key: ${{ secrets.PRIVATE_KEY }}
          script_stop: true
          script: |
            pwd
            ls -al
            cd ci_cd/actions-runner
            pwd
            if [[ "$(docker ps -q --filter ancestor=mysql:8.0)" ]]; then
              docker rm -f $(docker ps -qa --filter ancestor=mysql:8.0)
            fi
            echo "pass mysql-container"
            if [[ "$(docker ps -qa --filter ancestor=kdt1-study3-team4-back-cicd/kdt1-study3-team4-back:latest)" ]]; then
              docker rm -f $(docker ps -qa --filter ancestor=kdt1-study3-team4-back-cicd/kdt1-study3-team4-back:latest)
            fi
            echo "pass kdt1-study3-team4-back-cicd/kdt1-study3-team4-back:latest"
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GHCR_TOKEN }}
            docker pull ghcr.io/reberel/kdt1-study-3-team4-back:latest
            docker image prune -f
            docker logout
            
            docker-compose up -d
